version: '3.4'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"

  redis:
    container_name: redis
    image: redis:5.0.0
    ports:
      - "6379:6379"
    entrypoint: 
      redis-server --appendonly yes

  db:
    container_name: database
    image: postgres:11.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: 'bitnami/mongodb:4.1.4-ol-7-r10'
    container_name: mongodb
    ports:
      - "27017:27017"